### ISSUE TITLE
"target" not working, clicking behavior won't change

### ISSUE THREAD

**Issue by xiNeRoar** [walkxhub/homer-theme#12]
As title, I change all the "target" from "_blank" to "_self", but they still open in a new tab and won't open in the original tab.
I am running homer in docker on my Synology NAS ds920+

**Comment by walkxcode** [comment]
Hello. Please create an issue on the official homer GitHub  ( https://github.com/bastienwirtz/homer ). This issue is not related to my theme.

**Comment by xiNeRoar** [comment]
Thanks!
