### ISSUE TITLE
Text size

### ISSUE THREAD

**Issue by timknowlden** [walkxhub/homer-theme#13]
Hi, I soon run out of screen real estate, I currently have a whoogle search box which allows me to fit 6 items below and 4 columns, I'd like to shrink the size of text icons and outline boxes for each item, so i can fit more on any one page?

**Comment by timknowlden** [comment]
![screen](https://user-images.githubusercontent.com/73787006/162219704-73e93de3-19e9-4902-8372-9ce611633fd0.png)

**Comment by walkxcode** [comment]
Hello, I am just providing a theme. To change the configuration yourself, please refer to the [Official Homer documentation](https://github.com/bastienwirtz/homer).
