### ISSUE TITLE
Separate colors of normal text and message text

### ISSUE THREAD

**Issue by derderdunichbist** [walkxhub/homer-theme#15]
Hi there!
Is there a way to specify different colors for headings and the message-box text?

Right now, the property `colors -> light -> text` modifies both the headings of the different sections (e.g. Tools in the screenshot), but also the text color of the message box text, which makes it barely readable with the default color settings. 
The text in the message box is longer, I just selected bits of it for us to be readable.

![Screenshot 2022-05-05 at 11 54 25](https://user-images.githubusercontent.com/9165909/166900822-e01a28ea-ccc1-4061-8494-8087ae49e36b.png)

Thanks and best regards!

**Comment by walkxcode** [comment]
Hey!

You can do this by targeting the `.message-header` class for the header, and the `.message-body` class for the message itself in the custom.css file.

**Comment by derderdunichbist** [comment]
Thanks a lot! That solved my issue :)
